Create morse2beep
spkr-beep/beep pull request #16
Opened 2020-11-21 10:07 UTC by jidanni

(I'm not sure if my name or date or version belong in here. Feel free to remove them.)

2020-11-21 20:52 UTC, ndim commented
In case you do not want to install `perl`, `tr` and `sed` can help as well:

```sed
#!/usr/bin/env sed -f
# Usage:
#   cat text-file.txt | morse | tr '\n' '\r' | sed -f morse2beep.sed | xargs beep
#
i -l0 -D0
s/ daw\r\r/-n -l300 -D700 /g
s/ dit\r\r/-n -l100 -D700 /g
s/ daw\r/-n -l300 -D300 /g
s/ dit\r/-n -l100 -D300 /g
s/ daw/-n -l300 -D100 /g
s/ dit/-n -l100 -D100 /g
```

2020-11-21 21:07 UTC, jidanni commented
Ah, that is simply brilliant, @ndim.
I have an idea.
Make a subdirectory, contrib/morse
and rename my version to contrib/morse/morse2beep.pl,
and install your version as contrib/morse/morse2beep.sed !

2020-11-21 21:36 UTC, ndim commented
Thank *you* for the brilliant idea of converting morse code to beep parameters.

The sed script looks deceivingly simple, but it does several runs through the whole input, so it certainly will not be very efficient for long inputs. OTOH, nobody is going to transmit gigabytes of text in morse code via beep.

@jidanni Could you address the two things I have brought up in the review? Then I can pull that, add my sed script, and merge to master.

2020-11-21 21:47 UTC, jidanni commented
I would love to, if I could find it. What review?

2020-11-21 22:55 UTC, ndim requested changes
Uhm... can you see this now? (Still getting to know this github functionality.)

2020-11-21 22:57 UTC, ndim commented on contrib/morse2beep
> +# Turn Morse code into beeps.
(GPLv2 or MIT or Unlicense are fine, other license to be seen.)

2020-11-22 00:38 UTC, jidanni commented on contrib/morse2beep
> +    if    (/^...-.-$/) { die "Didn't get any input!" unless @elements; last; }
Gasp! I forgot the backslashes. Could you please put them in for me. I am sure to get tangled up in GitHub if I try.

Also I note you pass these "over and out" beeps, but I strip them. So maybe there should be an option added for folks who like their sound...

2020-11-22 00:39 UTC, jidanni commented on contrib/morse2beep
> +# Turn Morse code into beeps.
I usually just plaster in
`# Copyright       : https://www.fsf.org/copyleft/gpl.html`
but perhaps you could stick a better one in there for me. Thanks!

2020-11-22 00:43 UTC, jidanni commented on contrib/morse2beep
> +# Turn Morse code into beeps.
Also I suppose my Date and Version headers won't make too much sense now that editing has moved to GitHub. So maybe you can strip them. Thanks.

2020-11-22 01:13 UTC, ndim commented on contrib/morse2beep
> +# Turn Morse code into beeps.
So, changing the comment prefix from the `*.[ch]` " * " to "# ", would the following work for you?

```
# Copyright 2020 Dan Jacobson (https://www.jidanni.org/)
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
```

All the C code in beep is GPLv2 already, so beep already ships with a copy of the GPLv2.

The `Author`, `Created On`, `Last Modified On`, and `Update Count` lines could be removed then from my POV.

2020-11-22 01:19 UTC, jidanni commented on contrib/morse2beep
> +# Turn Morse code into beeps.
Looks great! Say, doesn't your sed version need a copyright too?
Also be sure to move all this to a contrib/morse/ subdirectory. Thanks.

2020-11-22 01:49 UTC, ndim commented on contrib/morse2beep
> +    if    (/^...-.-$/) { die "Didn't get any input!" unless @elements; last; }
I have interpreted the "sure to get tangled up in Github" remark as a suggestion to push the fixes for all the things we have talked about here to your [jidanni:patch-1](https://github.com/jidanni/beep/tree/patch-1) branch, so you can review them.

Regarding the trailing End Of Work (`...-.-`) I would say that for a `contrib/` script there is no need to write a fully fledged application. A reasonably documented script (and I have added notes to both the perl and the sed scripts regarding their respective way of handling of the End Of Work) is very fine for things in `contrib/`.

2020-11-22 01:50 UTC, ndim commented on contrib/morse2beep
> +# Turn Morse code into beeps.
All done in  [jidanni:patch-1](https://github.com/jidanni/beep/tree/patch-1).

2020-11-22 01:55 UTC, ndim commented
@jidanni As far as I can tell, I can basically merge this. Any more remarks before I do that?

2020-11-22 02:33 UTC, jidanni commented
OK, looks good from my tiny cell phone. Give it a rip!

2020-11-22 02:37 UTC, merged

2020-11-22 02:38 UTC, ndim commented
Thank you very much for the code, the idea, and the fruitful discussion!